from fpdf import FPDF
import pandas as pd


def generate_weekly_report(username, df):
    """Generate an enhanced PDF weekly study report with summary statistics."""
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Header
    pdf.set_font("Arial", "B", 20)
    pdf.cell(0, 12, "StudyVista Weekly Report", ln=True, align="C")
    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 8, f"Student: {username}", ln=True, align="C")

    # Date range
    dates = pd.to_datetime(df["date"])
    start = dates.min().strftime("%b %d, %Y")
    end = dates.max().strftime("%b %d, %Y")
    pdf.cell(0, 8, f"Period: {start} - {end}", ln=True, align="C")
    pdf.ln(6)

    # Summary Statistics
    pdf.set_font("Arial", "B", 14)
    pdf.set_fill_color(102, 126, 234)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 10, "  Summary", ln=True, fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", "", 11)
    pdf.ln(3)

    total_hours = df["study_hours"].sum()
    total_sessions = len(df)
    avg_focus = df["focus_level"].mean()
    subjects = df["subject"].nunique()

    stats = [
        f"Total Study Hours: {total_hours:.1f}h",
        f"Total Sessions: {total_sessions}",
        f"Average Focus Level: {avg_focus:.1f} / 5",
        f"Subjects Covered: {subjects}",
    ]
    for stat in stats:
        pdf.cell(0, 7, f"    {stat}", ln=True)
    pdf.ln(4)

    # Subject Breakdown
    pdf.set_font("Arial", "B", 14)
    pdf.set_fill_color(118, 75, 162)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 10, "  Subject Breakdown", ln=True, fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(3)

    subject_summary = df.groupby("subject").agg(
        {"study_hours": ["sum", "count"], "focus_level": "mean"}
    )
    subject_summary.columns = ["Hours", "Sessions", "Avg Focus"]
    subject_summary = subject_summary.sort_values("Hours", ascending=False)

    # Table header
    pdf.set_font("Arial", "B", 10)
    pdf.set_fill_color(230, 230, 240)
    pdf.cell(60, 8, "Subject", border=1, fill=True)
    pdf.cell(35, 8, "Hours", border=1, align="C", fill=True)
    pdf.cell(35, 8, "Sessions", border=1, align="C", fill=True)
    pdf.cell(40, 8, "Avg Focus", border=1, align="C", fill=True)
    pdf.ln()

    # Table rows
    pdf.set_font("Arial", "", 10)
    for subject, row in subject_summary.iterrows():
        pdf.cell(60, 7, str(subject), border=1)
        pdf.cell(35, 7, f"{row['Hours']:.1f}", border=1, align="C")
        pdf.cell(35, 7, str(int(row["Sessions"])), border=1, align="C")
        pdf.cell(40, 7, f"{row['Avg Focus']:.1f} / 5", border=1, align="C")
        pdf.ln()
    pdf.ln(4)

    # Daily Log
    pdf.set_font("Arial", "B", 14)
    pdf.set_fill_color(102, 126, 234)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 10, "  Daily Study Log", ln=True, fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(3)

    # Table header
    pdf.set_font("Arial", "B", 10)
    pdf.set_fill_color(230, 230, 240)
    pdf.cell(35, 8, "Date", border=1, fill=True)
    pdf.cell(50, 8, "Subject", border=1, fill=True)
    pdf.cell(30, 8, "Hours", border=1, align="C", fill=True)
    pdf.cell(30, 8, "Focus", border=1, align="C", fill=True)
    pdf.ln()

    # Table rows
    pdf.set_font("Arial", "", 10)
    for _, row in df.sort_values("date").iterrows():
        study_date = row["date"]
        if isinstance(study_date, pd.Timestamp):
            study_date = study_date.strftime("%b %d, %Y")
        else:
            study_date = str(study_date)

        pdf.cell(35, 7, study_date, border=1)
        pdf.cell(50, 7, str(row["subject"]), border=1)
        pdf.cell(30, 7, f"{row['study_hours']:.1f}", border=1, align="C")
        pdf.cell(30, 7, f"{row['focus_level']} / 5", border=1, align="C")
        pdf.ln()

    pdf.ln(6)

    # Footer
    pdf.set_font("Arial", "I", 9)
    pdf.set_text_color(128, 128, 128)
    pdf.cell(0, 8, "Generated by StudyVista - Track . Analyze . Improve", ln=True, align="C")

    pdf_bytes = pdf.output(dest="S").encode("latin-1")
    return pdf_bytes
